# Form implementation generated from reading ui file 'addEditCoffeeForm.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_AddEditCoffeeForm(object):
    def setupUi(self, AddEditCoffeeForm):
        AddEditCoffeeForm.setObjectName("AddEditCoffeeForm")
        AddEditCoffeeForm.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(AddEditCoffeeForm)
        self.verticalLayout.setObjectName("verticalLayout")
        self.nameInput = QtWidgets.QLineEdit(parent=AddEditCoffeeForm)
        self.nameInput.setObjectName("nameInput")
        self.verticalLayout.addWidget(self.nameInput)
        self.roastInput = QtWidgets.QComboBox(parent=AddEditCoffeeForm)
        self.roastInput.setObjectName("roastInput")
        self.verticalLayout.addWidget(self.roastInput)
        self.typeInput = QtWidgets.QComboBox(parent=AddEditCoffeeForm)
        self.typeInput.setObjectName("typeInput")
        self.verticalLayout.addWidget(self.typeInput)
        self.flavorInput = QtWidgets.QLineEdit(parent=AddEditCoffeeForm)
        self.flavorInput.setObjectName("flavorInput")
        self.verticalLayout.addWidget(self.flavorInput)
        self.priceInput = QtWidgets.QSpinBox(parent=AddEditCoffeeForm)
        self.priceInput.setMinimum(0)
        self.priceInput.setMaximum(10000)
        self.priceInput.setObjectName("priceInput")
        self.verticalLayout.addWidget(self.priceInput)
        self.volumeInput = QtWidgets.QSpinBox(parent=AddEditCoffeeForm)
        self.volumeInput.setMinimum(0)
        self.volumeInput.setMaximum(1000)
        self.volumeInput.setObjectName("volumeInput")
        self.verticalLayout.addWidget(self.volumeInput)
        self.saveButton = QtWidgets.QPushButton(parent=AddEditCoffeeForm)
        self.saveButton.setObjectName("saveButton")
        self.verticalLayout.addWidget(self.saveButton)

        self.retranslateUi(AddEditCoffeeForm)

    def retranslateUi(self, AddEditCoffeeForm):
        _translate = QtCore.QCoreApplication.translate
        AddEditCoffeeForm.setWindowTitle(_translate("AddEditCoffeeForm", "Добавить/Редактировать кофе"))
        self.nameInput.setPlaceholderText(_translate("AddEditCoffeeForm", "Название сорта"))
        self.flavorInput.setPlaceholderText(_translate("AddEditCoffeeForm", "Описание вкуса"))
        self.saveButton.setText(_translate("AddEditCoffeeForm", "Сохранить"))
